updated with parameter

diff --git a/check_mule b/check_mule
--- a/check_mule
+++ b/check_mule
@@ -1,12 +1,40 @@
 #!/bin/bash
 
-SERVICE=$1
+# Default values
+HOST=""
+SERVICE=""
+
+# Parse command line options
+while getopts ":c:H:" opt; do
+  case $opt in
+    c)
+      SERVICE="$OPTARG"
+      ;;
+    H)
+      HOST="$OPTARG"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+# Check if required options are provided
+if [ -z "$SERVICE" ] || [ -z "$HOST" ]; then
+  echo "Usage: $(basename "$0") -c <service> -H <host>"
+  exit 1
+fi
 
 # Check if the service is running
-if ps ax | grep -v grep | grep -v "$0" | grep -q "$SERVICE"; then
-    echo "OK - $SERVICE service is running"
+if ssh "$HOST" "ps ax | grep -v grep | grep -q $SERVICE"; then
+    echo "OK - $SERVICE service is running on $HOST"
     exit 0  # Exit with status 0 (OK)
 else
-    echo "CRITICAL - $SERVICE service is not running"
+    echo "CRITICAL - $SERVICE service is not running on $HOST"
     exit 2  # Exit with status 2 (CRITICAL)
 fi
